import * as uuid from "uuid";
import {
  ButtonSchema,
  CardSchema,
  CheckBoxSchema,
  ComponentItem,
  DesignerComponent,
  DesignerEventType,
  DialogSchema,
  FormItemSchema,
  InputSchema,
  ProductSchema,
  RadioSchema,
  SelectSchema,
  SwitchSchema,
} from "./schema";

export const visibleRuleOperationList = ["==", "!=", ">", ">=", "<", "<="];

export const componentList: ComponentItem[] = [
  {
    component: DesignerComponent.Card,
    name: "卡片组件",
    type: "container",
    init: () =>
      ({
        id: uuid.v4(),
        component: DesignerComponent.Card,
        visibleRule: {},
        visible: true,
        title: "卡片标题",
        showTitle: true,
        background: "white",
        content: "",
        children: [],
      } as CardSchema),
  },
  {
    component: DesignerComponent.FormItem,
    name: "表单样式组件",
    type: "container",
    init: () =>
      ({
        id: uuid.v4(),
        component: DesignerComponent.FormItem,
        visibleRule: {},
        visible: true,
        label: "字段名",
        labelWidth: 100,
        showLabel: true,
        tip: "",
        children: [],
      } as FormItemSchema),
  },
  {
    component: DesignerComponent.Button,
    name: "按钮组件",
    type: "container",
    init: () =>
      ({
        id: uuid.v4(),
        component: DesignerComponent.Button,
        visibleRule: {},
        visible: true,
        text: "按钮",
        type: "primary",
        disabled: false,
        eventList: [],
      } as ButtonSchema),
  },
  {
    component: DesignerComponent.Input,
    name: "输入框组件",
    type: "formItem",
    init: key =>
      ({
        id: uuid.v4(),
        key: key,
        component: DesignerComponent.Input,
        visibleRule: {},
        visible: true,
        label: "标签",
        showLabel: true,
        tip: "",
        defaultValue: "",
        required: false,
        disabled: false,
        editDisabled: false,
        rules: [],
        placeholder: "",
        type: "text",
        maxLength: 10000,
        autosize: { minRows: 1, maxRows: 100 },
        showCopy: false,
      } as InputSchema),
  },
  {
    component: DesignerComponent.Select,
    name: "下拉框组件",
    type: "formItem",
    init: key =>
      ({
        id: uuid.v4(),
        key: key,
        component: DesignerComponent.Select,
        visibleRule: {},
        visible: true,
        label: "标签",
        showLabel: true,
        tip: "",
        defaultValue: "",
        required: false,
        disabled: false,
        editDisabled: false,
        rules: [],
        placeholder: "",
        multiple: false,
        options: [
          {
            label: "选项一",
            value: "1",
          },
          {
            label: "选项二",
            value: "2",
          },
        ],
      } as SelectSchema),
  },
  {
    component: DesignerComponent.Radio,
    name: "单选框组件",
    type: "formItem",
    init: key =>
      ({
        id: uuid.v4(),
        key: key,
        component: DesignerComponent.Radio,
        visibleRule: {},
        visible: true,
        label: "标签",
        showLabel: true,
        tip: "",
        defaultValue: "",
        required: false,
        disabled: false,
        editDisabled: false,
        rules: [],
        options: [
          {
            label: "选项一",
            value: "1",
          },
          {
            label: "选项二",
            value: "2",
          },
        ],
      } as RadioSchema),
  },
  {
    component: DesignerComponent.Switch,
    name: "开关组件",
    type: "formItem",
    init: key =>
      ({
        id: uuid.v4(),
        key: key,
        component: DesignerComponent.Switch,
        visibleRule: {},
        visible: true,
        label: "标签",
        showLabel: true,
        tip: "",
        defaultValue: "",
        required: false,
        disabled: false,
        editDisabled: false,
        rules: [],
        activeText: "",
      } as SwitchSchema),
  },
  {
    component: DesignerComponent.CheckBox,
    name: "多选框组件",
    type: "formItem",
    init: key =>
      ({
        id: uuid.v4(),
        key: key,
        component: DesignerComponent.CheckBox,
        visibleRule: {},
        visible: true,
        label: "标签",
        showLabel: true,
        tip: "",
        defaultValue: [],
        required: false,
        disabled: false,
        editDisabled: false,
        rules: [],
        options: [
          {
            label: "选项一",
            value: "1",
          },
          {
            label: "选项二",
            value: "2",
          },
        ],
      } as CheckBoxSchema),
  },
];

export const dialogComponent: ComponentItem = {
  component: DesignerComponent.Dialog,
  name: "对话框组件",
  type: "container",
  init: () =>
    ({
      id: uuid.v4(),
      component: DesignerComponent.Dialog,
      visibleRule: {},
      visible: true,
      dialogVisible: true,
      title: "对话框标题",
      showTitle: true,
      content: "",
      children: [],
      buttonList: [],
    } as DialogSchema),
};

export const productMap: Record<string, ProductSchema> = {
  test_product: {
    labelWidth: "100px",
    components: [
      {
        id: "card_白板",
        component: DesignerComponent.Card,
        visibleRule: {},
        visible: true,
        title: "白板",
        showTitle: true,
        background: "white",
        children: [
          {
            id: "input_name",
            component: DesignerComponent.Input,
            visibleRule: {},
            visible: true,
            label: "名称",
            showLabel: true,
            key: "name",
            tip: "我是字段的描述",
            defaultValue: "{{netless.appid}}",
            required: false,
            disabled: true,
            editDisabled: false,
            rules: [],
            placeholder: "请输入名称",
            type: "text",
            maxLength: 100,
            autosize: false,
            showCopy: false,
          } as InputSchema,
          {
            id: "formItem_1_1",
            component: DesignerComponent.FormItem,
            visibleRule: {},
            visible: true,
            label: "SDK Token",
            labelWidth: 100,
            showLabel: true,
            tip: "",
            children: [
              {
                id: "button1",
                component: DesignerComponent.Button,
                visibleRule: {},
                visible: true,
                type: "text",
                text: "更新token",
                disabled: false,
                eventList: [
                  {
                    type: DesignerEventType.OpenDialog,
                    params: {
                      dialogId: "dialog1",
                    },
                  },
                ],
              } as ButtonSchema,
            ],
          } as FormItemSchema,
          {
            id: "formItem_1_2",
            component: DesignerComponent.FormItem,
            visibleRule: {},
            visible: true,
            label: "存储配置",
            labelWidth: 100,
            showLabel: true,
            tip: "",
            children: [
              {
                id: "card_存储配置",
                component: DesignerComponent.Card,
                visibleRule: {},
                visible: true,
                title: "",
                showTitle: false,
                background: "gray",
                children: [
                  {
                    id: "vendor",
                    component: DesignerComponent.Select,
                    visibleRule: {},
                    visible: true,
                    label: "vendor",
                    showLabel: true,
                    key: "vendor",
                    tip: "",
                    defaultValue: "0",
                    required: true,
                    disabled: false,
                    editDisabled: false,
                    rules: [],
                    placeholder: "",
                    multiple: false,
                    options: [
                      {
                        value: "0",
                        label: "Aliyun OSS",
                      },
                      {
                        value: "1",
                        label: "AWS S3",
                      },
                    ],
                  } as SelectSchema,
                  {
                    id: "input_region",
                    component: DesignerComponent.Input,
                    visibleRule: { "==": [{ var: "formValue.vendor" }, "0"] },
                    visible: false,
                    label: "region",
                    showLabel: true,
                    key: "region",
                    tip: "",
                    defaultValue: "",
                    required: false,
                    disabled: false,
                    editDisabled: false,
                    rules: [],
                    placeholder: "region",
                    type: "text",
                    maxLength: 100,
                    autosize: false,
                    showCopy: false,
                  } as InputSchema,
                  {
                    id: "input_region_aws",
                    component: DesignerComponent.Input,
                    visibleRule: { "==": [{ var: "formValue.vendor" }, "1"] },
                    visible: false,
                    label: "region_aws",
                    showLabel: true,
                    key: "region_aws",
                    tip: "",
                    defaultValue: "",
                    required: false,
                    disabled: false,
                    editDisabled: false,
                    rules: [],
                    placeholder: "region_aws",
                    type: "text",
                    maxLength: 100,
                    autosize: false,
                    showCopy: false,
                  } as InputSchema,
                  {
                    id: "input_endpoint",
                    component: DesignerComponent.Input,
                    visibleRule: { "==": [{ var: "formValue.vendor" }, "0"] },
                    visible: false,
                    label: "endpoint",
                    showLabel: true,
                    key: "endpoint",
                    tip: "",
                    defaultValue: "",
                    required: false,
                    disabled: false,
                    editDisabled: false,
                    rules: [],
                    placeholder: "endpoint",
                    type: "text",
                    maxLength: 100,
                    autosize: false,
                    showCopy: false,
                  } as InputSchema,
                  {
                    id: "input_endpoint_aws",
                    component: DesignerComponent.Input,
                    visibleRule: { "==": [{ var: "formValue.vendor" }, "1"] },
                    visible: false,
                    label: "endpoint_aws",
                    showLabel: true,
                    key: "endpoint_aws",
                    tip: "",
                    defaultValue: "",
                    required: false,
                    disabled: false,
                    editDisabled: false,
                    rules: [],
                    placeholder: "endpoint_aws",
                    type: "text",
                    maxLength: 100,
                    autosize: false,
                    showCopy: false,
                  } as InputSchema,
                ],
              } as CardSchema,
            ],
          } as FormItemSchema,
        ],
      } as CardSchema,
      {
        id: "card_2",
        component: DesignerComponent.Card,
        visibleRule: {},
        visible: true,
        title: "云录制",
        showTitle: true,
        background: "white",
        children: [
          {
            id: "radio_recordConfig",
            component: DesignerComponent.Radio,
            visibleRule: {},
            visible: true,
            label: "录制配置",
            showLabel: true,
            key: "recordConfig",
            tip: "",
            defaultValue: "0",
            required: true,
            disabled: false,
            editDisabled: false,
            rules: [],
            options: [
              {
                value: "0",
                label: "默认",
              },
              {
                value: "1",
                label: "自定义",
              },
              {
                value: "3",
                label: "禁止",
                disabled: true,
              },
            ],
          } as RadioSchema,
          {
            id: "input_recordCustomConfig",
            component: DesignerComponent.Input,
            visibleRule: { "==": [{ var: "formValue.recordConfig" }, "1"] },
            visible: false,
            label: "自定义配置",
            showLabel: false,
            key: "recordCustomConfig",
            tip: "",
            defaultValue: "",
            required: true,
            disabled: false,
            editDisabled: false,
            rules: [],
            placeholder: '"maxIdleTime": 30',
            type: "textarea",
            maxLength: 100,
            autosize: {
              minRows: 2,
              maxRows: 5,
            },
            showCopy: false,
          } as InputSchema,
        ],
      } as CardSchema,
      {
        id: "card_3",
        component: DesignerComponent.Card,
        visibleRule: {},
        visible: true,
        title: "test",
        showTitle: true,
        background: "white",
        children: [
          {
            id: "switch",
            component: DesignerComponent.Switch,
            visibleRule: {},
            visible: true,
            label: "Switch",
            showLabel: true,
            key: "switch",
            tip: "",
            defaultValue: "",
            required: true,
            disabled: false,
            editDisabled: false,
            rules: [],
            activeText: "",
          } as SwitchSchema,
          {
            id: "checkbox",
            component: DesignerComponent.CheckBox,
            visibleRule: {},
            visible: true,
            label: "Checkbox",
            showLabel: true,
            key: "checkbox",
            tip: "",
            defaultValue: "",
            required: true,
            disabled: false,
            editDisabled: false,
            rules: [],
            options: [
              {
                value: "0",
                label: "默认",
              },
              {
                value: "1",
                label: "自定义",
              },
              {
                value: "3",
                label: "禁止",
                disabled: true,
              },
            ],
          } as CheckBoxSchema,
          {
            id: "select",
            component: DesignerComponent.Select,
            visibleRule: {},
            visible: true,
            label: "Select",
            showLabel: true,
            key: "select",
            tip: "",
            defaultValue: "",
            required: true,
            disabled: false,
            editDisabled: false,
            rules: [],
            placeholder: "",
            multiple: true,
            options: [
              {
                value: "0",
                label: "默认",
              },
              {
                value: "1",
                label: "自定义",
              },
              {
                value: "3",
                label: "禁止",
                disabled: true,
              },
            ],
          } as SelectSchema,
        ],
      } as CardSchema,
      {
        id: "form_button1",
        component: DesignerComponent.Button,
        visibleRule: {},
        visible: true,
        type: "primary",
        text: "提交",
        disabled: false,
        eventList: [
          {
            type: DesignerEventType.SubmitForm,
            params: {
              keyList: ["name", "region"],
            },
          },
        ],
      } as ButtonSchema,
    ],
    dialogList: [],
  },
};

export const commonRules = [
  {
    rule: "^[0-9]*$",
    label: "纯数字",
  },
  {
    rule: "^[A-Za-z0-9]+$",
    label: "英文、数字",
  },
  {
    rule: "^[\u4E00-\u9FA5A-Za-z0-9_]+$",
    label: "中文、英文、数字包括下划线",
  },
  {
    rule: "^\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$",
    label: "邮箱",
  },
  {
    rule: "^(https?:\\/\\/(([a-zA-Z0-9]+-?)+[a-zA-Z0-9]+\\.)+[a-zA-Z]+)(:\\d+)?(\\/.*)?(\\?.*)?(#.*)?$",
    label: "URL",
  },
  {
    rule: "\\d+\\.\\d+\\.\\d+\\.\\d+",
    label: "IP 地址",
  },
  {
    rule: "^(13[0-9]|14[0-9]|15[0-9]|16[0-9]|17[0-9]|18[0-9]|19[0-9])\\d{8}$",
    label: "手机号码",
  },
];
